apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project1
  namespace: argocd
spec:
  sourceRepos:
    - 'https://github.com/tatimun/app2-gitops.git'
  destinations:
    - namespace: project1
      server: 'https://kubernetes.default.svc'
