apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project1
  namespace: openshift-gitops
spec:
  sourceRepos:
    - '*' 
  destinations:
    - namespace: project1
      server: 'https://kubernetes.default.svc'
