apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project2
  namespace: openshift-gitops
spec:
  sourceRepos:
    - 'https://github.com/tatimun/app2-gitops.git'
  destinations:
    - namespace: project2
      server: 'https://kubernetes.default.svc'
