apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project3
  namespace: openshift-gitops
spec:
  description: Proyecto por defecto para todas las aplicaciones
  sourceRepos:
    - 'https://github.com/tatimun/app2-gitops.git' # Permite cualquier repositorio Git
  destinations:
    - namespace: '*' # Permite cualquier namespace
      server: 'https://kubernetes.default.svc' # Cluster local
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceBlacklist:
    - group: '*'
      kind: 'Secret' # Ejemplo: Bloquea la gestión de secretos