apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: homebanking  # Nombre del ApplicationSet
  namespace: openshift-gitops
spec:
  generators:
    - list:
        elements:
          - name: homebanking-desa  # Nombre único para cada aplicación
            namespace: project1
            path: overlays/desa
          - name: homebanking-homo
            namespace: project2
            path: overlays/homo
          - name: homebanking-prod
            namespace: project3
            path: overlays/prod
  template:
    metadata:
      name: '{{name}}'  # Usa el nombre definido en el generador
    spec:
      project: '{{namespace}}'
      source:
        repoURL: 'https://github.com/tatimun/app2-gitops.git'
        targetRevision: HEAD
        path: '{{path}}'  # Usa la ruta definida en el gener
