apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: projects-appset
  namespace: project1
spec:
  generators:
    - git:
        repoURL: 'https://github.com/tatimun/openshift-gitops'
        directories:
          - path: 'applications/*'
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: '{{path.basename}}'
      source:
        repoURL: 'https://github.com/tatimun/openshift-gitops'
        path: 'applications/{{path.basename}}'
        targetRevision: HEAD
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{path.basename}}-namespace'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
